### ISSUE TITLE
Extend HmmProbabilities interface to include the observation

### ISSUE THREAD

**Issue by karussell** [bmwcarit/hmm-lib#1]
To integrate this with GraphHopper we would need the TimeStep.observation. See
- https://github.com/michaz/hmm-lib/commit/3369c984aa412790439f6cfa39378904227d8f02
- https://github.com/graphhopper/map-matching/blob/demoui/matching-core/src/main/java/com/graphhopper/matching/MapMatchingHmmProbabilities.java#L66

Is it possible to integrate this into upstream?

**Comment by stefanholder** [comment]
Sorry for the late reply.

The change looks good to me. Can you please create a pull request?

**Comment by stefanholder** [comment]
I just merged the pull request.
